services:

  traefik:
    container_name: traefik
    image: traefik:v3.6.4
    ports:
     - "80:80"
     - "443:443"
    environment:
      - DEVBOX_HOSTNAME=${DEVBOX_HOSTNAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${DEVBOX_HOSTNAME}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
    volumes:
      - traefik-certs:/certs:rw
      - ./config:/etc/traefik:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    privileged: true
    # bypass userns-remap
    userns_mode: 'host'
    restart: unless-stopped

volumes:
  traefik-certs:
    name: traefik-certs

networks:
  default:
    name: devbox
    external: true

